spring.application.name=solar
spring.datasource.url=jdbc:postgresql://localhost:5432/solar
spring.datasource.username=postgres
spring.datasource.password=Danik1311
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

solar.provider.foxess.url=https://api.foxesscloud.com/op/v0/device/history/query
solar.provider.foxess.path=/op/v0/device/history/query

solar.provider.forecast-solar.url=https://api.forecast.solar/estimate

solar.provider.open-meteo.url=https://api.open-meteo.com/v1/forecast
solar.provider.open-meteo.efficiency=0.85
solar.provider.open-meteo.default-capacity=5.0

